[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SUPABASE_URL = "https://faqmigkktzmdtloozevi.supabase.co"
  SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcW1pZ2trdHptZHRsb296ZXZpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDU5MDU5MiwiZXhwIjoyMDY2MTY2NTkyfQ.RTWX4XPdUc2_1iNk_WFkRNhTirJDcXG7mjqvdnc7MaA"

[functions]
  node_bundler = "esbuild"
  timeout = 30